[package]
name = "sdl2_engine"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
swarm_pool = "0.1.9"

[dependencies.sdl2]
version = "*"
default-features = false
features = ["image"]